{
 "title": "Sensors",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PM 2.5",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  pmtwofive\nFROM airquality\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "PM 10",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  pmten\nFROM airquality\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  co2level\nFROM co2\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  (temp_indoor * 9/5 + 32) AS temp_indoor\nFROM temperature\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  { "title": "Mobile Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Mobile CO2",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  co2level\nFROM mobileco2\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Mobile Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  (temp * 9/5 + 32) AS temp\nFROM mobiletemperature\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}